# Generated by Django 5.0.4 on 2024-07-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_name_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_scan', models.FileField(upload_to='photo', verbose_name='photo')),
                ('alimony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='products.product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
    ]
