# Generated by Django 5.0.4 on 2024-07-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Photo',
        ),
    ]
