# Generated by Django 5.0.4 on 2024-07-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_document_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
