# Generated by Django 5.0.4 on 2024-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='document_scan',
            field=models.FileField(upload_to='myproject/photo', verbose_name='photo'),
        ),
    ]
