# Generated by Django 5.0.4 on 2024-07-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_photo_document_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alimony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_glass_photo', to='products.product'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='document_scan',
            field=models.FileField(upload_to='photo', verbose_name='photos'),
        ),
    ]
