# Generated by Django 5.0.4 on 2024-07-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_photo_alimony_alter_photo_document_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='document_scan',
            field=models.FileField(upload_to='suratlar', verbose_name='photos'),
        ),
    ]
