# Generated by Django 5.0.4 on 2024-07-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_photo_document_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='alimony',
            new_name='Product',
        ),
    ]
