# Generated by Django 5.0.4 on 2024-07-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_alimony_photo_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='document_scan',
            new_name='photo',
        ),
    ]
