# Generated by Django 5.0.4 on 2024-07-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_document_scan_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='products.product'),
        ),
    ]
