# Generated by Django 5.0.4 on 2024-07-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_photo_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='suratlar', verbose_name='photos')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img2', to='products.product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
        migrations.DeleteModel(
            name='Photo_3',
        ),
    ]
