# Generated by Django 5.0.4 on 2024-07-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_photo_2_delete_photo_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_2',
            options={'verbose_name': 'photo2', 'verbose_name_plural': 'photo2'},
        ),
        migrations.CreateModel(
            name='Photo_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='suratlar', verbose_name='photos')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img3', to='products.product')),
            ],
            options={
                'verbose_name': 'photo3',
                'verbose_name_plural': 'photo3',
            },
        ),
    ]
