# Generated by Django 5.0.1 on 2024-09-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory',
        ),
    ]
